### ISSUE TITLE
Missing BackboneData ?

### ISSUE THREAD

**Issue by Vincentx15** [vsomnath/holoprot#7]
Hello, 

Thanks for the work and clean repo. I wanted to use your processed data for the EC task, with my own models. I untared raw and processed surface2backbone. However, there seems to be a missing class in the data/base.py. Indeed, when I try to load the data using the following code : 

```python
if __name__ == '__main__':
    raw_dir = os.path.abspath(f"../../data/enzyme/")
    processed_dir = os.path.abspath(f"../../data/")
    train_dataset = EnzymeDataset(mode='train', raw_dir=raw_dir,
                                  processed_dir=processed_dir,
                                  add_targets=True,
                                  prot_mode='surface2backbone')
    item = train_dataset[0]
``` 

I get the following error : 
```bash
Traceback (most recent call last):
  File "/home/vmallet/anaconda3/envs/atom2d/lib/python3.8/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/vmallet/anaconda3/envs/atom2d/lib/python3.8/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/home/vmallet/anaconda3/envs/atom2d/lib/python3.8/site-packages/torch/serialization.py", line 1124, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'BackboneData' on <module 'holoprot.data.base' from '/home/vmallet/projects/atom2d/atom2d/holoprot/data/base.py'>
```

Do you think this class definition could be missing ? Also, am I using the right loading ? I am trying to retrieve the meshes, residue graphs and node/vertices features that you used for training.

Thanks a ton in advance for your help !

Best,
Vincent

**Comment by vsomnath** [comment]
Hi, 

Thanks for reaching out! -- I think some classes used to be named differently before, and the data was processed with that. Let me have a look at this and correct the dataclasses if necessary and reupload.

Thanks,
Vignesh

**Comment by Vincentx15** [comment]
Ok thanks a ton ! And will this procedure give me the meshes and graphs + features as expected or should I proceed differently ?

**Comment by vsomnath** [comment]
Yes, I think if you specified `prot_mode` as `surface2backbone` this should construct the full hierarchical graph.

**Comment by Vincentx15** [comment]
Hello, do you have any updates ? I think it is just a matter of releasing another version of your private repository where you had a BackboneData class, is it not ? Or maybe updating the data ?

Please let me know if you think it will eventually work, otherwise I will start the process of trying to create the data from scratch on my end !

Best,
Vincent

**Comment by lmqfly** [comment]
I have the same problem, AttributeError: Can't get attribute 'BackboneData' on <module 'holoprot.data.base'
